version: '2'
services:
    redis:
        #build:
        #    context: https://github.com/xiaoyawl/docker-redis.git
        container_name: redis_server
        restart: always
        command: ["redis-server", "/etc/redis.conf"]
        privileged: true
        image: benyoo/redis:3.2.3
        ports:
        - "127.0.0.1:6379:6379"
        environment:
        - TERM=linux
        volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/redis.conf:/etc/redis.conf:ro
        - /data/redis:/data/redis:Z
    php:
        #build:
        #    context: https://github.com/xiaoyawl/docker-php.git
        container_name: php_server
        restart: always
        #privileged: true
        image: benyoo/php:5.6.24
        links:
        - redis:resid_server
        environment:
        - REDIS=Yes
        - MEMCACHE=Yes
        - SWOOLE=Yes
        volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data/wwwroot:/data/wwwroot:rw
    nginx:
        #build:
        #    context: https://github.com/xiaoyawl/docker-nginx.git
        container_name: nginx_server
        restart: always
        #privileged: true
        image: benyoo/nginx:1.10.1
        ports:
        - "80:80"
        - "443:443"
        links:
        - php:php_server
        - redis:resid_server
        volumes_from:
        - php
        environment:
        - PHP_FPM=Yes
        - PHP_FPM_SERVER=php_server
        - PHP_FPM_PORT=9000
        volumes:
        - /etc/localtime:/etc/localtime:ro
        - /data/wwwroot:/data/wwwroot:rw
        - /data/wwwlogs:/data/wwwlogs:rw
        - /data/conf/nginx/vhost:/usr/local/nginx/conf/vhost:rw
